# Generated by Django 4.0.4 on 2022-04-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hash_senha', models.CharField(max_length=73)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao_produto', models.TextField(max_length=500)),
                ('telefone1', models.CharField(max_length=11)),
                ('telefone2', models.CharField(max_length=11)),
                ('descricao_telefone', models.CharField(max_length=25)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificados_na_web.cliente')),
            ],
        ),
    ]
