# Generated by Django 4.0.4 on 2022-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificados_na_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='valor_anuncio',
            field=models.DecimalField(choices=[(2.0, 'Anúncio simples'), (5.0, 'Anúncio destaque de página')], decimal_places=2, default=2.0, max_digits=10, verbose_name='Tipo de anúncio'),
        ),
    ]
