# Generated by Django 4.0.4 on 2022-04-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificados_na_web', '0002_anuncio_valor_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidadePalavras', models.PositiveIntegerField()),
                ('imagem', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='descricao_produto',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='descricao_telefone',
            new_name='observacao',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='valor_produto',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='valor_anuncio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
