# Generated by Django 4.0.4 on 2022-04-24 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classificados_na_web', '0004_anuncio_categoria_anuncio_tipo_anuncio_anuncio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
