# Generated by Django 4.0.4 on 2022-04-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classificados_na_web', '0005_alter_anuncio_id_alter_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.ManyToManyField(help_text='Exemplo', to='classificados_na_web.categoria'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descricao',
            field=models.TextField(blank=True, help_text='Exemplo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='observacao',
            field=models.CharField(blank=True, help_text='Exemplo', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='telefone1',
            field=models.CharField(help_text='Exemplo', max_length=11),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='telefone2',
            field=models.CharField(blank=True, help_text='Exemplo', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_anuncio',
            field=models.ForeignKey(help_text='Exemplo', null=True, on_delete=django.db.models.deletion.CASCADE, to='classificados_na_web.tipoanuncio'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(help_text='Exemplo', max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Exemplo', max_digits=10),
        ),
    ]
